//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PontoRemoto.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PontoRemoto.Application.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações do cliente alteradas com sucesso.
        /// </summary>
        public static string ClientConfigurationUpdated {
            get {
                return ResourceManager.GetString("ClientConfigurationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um cliente associado a este CPF.
        /// </summary>
        public static string ClientIdentificationAlreadyExists {
            get {
                return ResourceManager.GetString("ClientIdentificationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A identificação só deve conter letras e números e sem espaços.
        /// </summary>
        public static string ClientIdentificationInvalid {
            get {
                return ResourceManager.GetString("ClientIdentificationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um cliente associado a este email.
        /// </summary>
        public static string ClientUsernameAlreadyExists {
            get {
                return ResourceManager.GetString("ClientUsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse dispositivo foi bloqueado.
        /// </summary>
        public static string DeviceBlocked {
            get {
                return ResourceManager.GetString("DeviceBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse dispositivo não foi cadastrado.
        /// </summary>
        public static string DeviceInvalid {
            get {
                return ResourceManager.GetString("DeviceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido.
        /// </summary>
        public static string EmailAddressInvalidError {
            get {
                return ResourceManager.GetString("EmailAddressInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao executar essa ação.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso permitido com sucesso.
        /// </summary>
        public static string GrantAccessSuccess {
            get {
                return ResourceManager.GetString("GrantAccessSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha incorretos.
        /// </summary>
        public static string LoginInvalid {
            get {
                return ResourceManager.GetString("LoginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; é obrigatório.
        /// </summary>
        public static string MandatoryFieldError {
            get {
                return ResourceManager.GetString("MandatoryFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; deve ser um número inteiro.
        /// </summary>
        public static string MustBeInteger {
            get {
                return ResourceManager.GetString("MustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha foi alterada com sucesso.
        /// </summary>
        public static string PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha incorreta.
        /// </summary>
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não foi confirmada.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível criar a conta: {0}.
        /// </summary>
        public static string RegisterAccountError {
            get {
                return ResourceManager.GetString("RegisterAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua conta foi criada com sucesso.
        /// </summary>
        public static string RegisterAccountSuccess {
            get {
                return ResourceManager.GetString("RegisterAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso revogado com sucesso.
        /// </summary>
        public static string RevokeAccessSuccess {
            get {
                return ResourceManager.GetString("RevokeAccessSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ter entre {2} e {1} caracteres.
        /// </summary>
        public static string StringLengthError {
            get {
                return ResourceManager.GetString("StringLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário associado a esse dispositivo.
        /// </summary>
        public static string WorkerDeviceIdAlreadyExists {
            get {
                return ResourceManager.GetString("WorkerDeviceIdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário não encontrado.
        /// </summary>
        public static string WorkerNotFound {
            get {
                return ResourceManager.GetString("WorkerNotFound", resourceCulture);
            }
        }
    }
}
